#!/bin/bash


usage() {
    echo "Arguments: [ge]neral [cm]d [kn]owledge [ba]sh [so]ftware [ma]kefile [ne]twork [pa]th [sq]l [de]vop"

}
open() {
    path="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
    case "$1" in 
        ge|general)
            nvim ${path}/doc/general.md
            ;;
        cm|cmd)
            nvim ${path}/doc/cmd.md
            ;;
        kn|knowledge)
            nvim ${path}/doc/knowledge.md
            ;;
        ba|bash)
            nvim ${path}/doc/bash.md
            ;;
        so|software)
            nvim ${path}/doc/software.md
            ;;
        ma|makefile)
            nvim ${path}/doc/makefile.md
            ;;
		ne|net|network)
			nvim ${path}/doc/network.md
			;;
		pa|path)
			nvim ${path}/doc/path.md
			;;
		sq|sql)
			nvim ${path}/doc/sql.md
			;;
		de|devop)
			nvim ${path}/doc/devop.md
			;;
        *)
            usage
            ;;
    esac
}


open "$@"

