#!/bin/bash


usage() {
    echo "Arguments: [ge]neral [cm]d [kn]owledge [ba]sh [so]ftware [ma]kefile"

}
open() {
    path="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
    case "$1" in 
        ge|general)
            nvim ${path}/doc/general
            ;;
        cm|cmd)
            nvim ${path}/doc/cmd
            ;;
        kn|knowledge)
            nvim ${path}/doc/knowledge
            ;;
        ba|bash)
            nvim ${path}/doc/bash
            ;;
        so|software)
            nvim ${path}/doc/software
            ;;
        ma|makefile)
            nvim ${path}/doc/makefile
            ;;
        *)
            usage
            ;;
    esac
}


open "$@"

